inherits = "base16_transparent"

# "ui.selection" = { fg = "white", bg = "gray" }
# "ui.cursor" = { fg = "black", bg = "light-gray" }
# "ui.cursor.primary" = { fg = "black", bg = "light-gray" }
# "ui.cursor.match" = { modifiers = ["underlined"] }
# "ui.background.separator" = "gray"
# "ui.linenr" = "gray"
# "ui.linenr.selected" = { fg = "white", bg = "gray" }
# "ui.statusline" = { bg = "black", fg = "white" }
# "ui.menu" = { fg = "white", bg = "black" }
# "ui.menu.selected" = { bg = "light-gray", fg = "black" }
# "ui.popup" = { fg = "white", bg = "black" }
# "ui.help" = { fg = "white", bg = "black" }
# "ui.virtual.ruler" = { underline = { style = "line"} }

"string" = { bg = "#44916f", fg = "black" }
"constant" = { bg = "light-cyan", fg = "black" }
"comment" = { bg = "#c29470", fg = "black" }
"constructor" = { fg = "purple1", bg="red1" }
# "diff.plus" = "green"
# "diff.minus" = "red"
# "diff.delta" = "gray"

# "warning" = { fg = "black", bg = "light-yellow" }
"error" = { fg = "white", bg = "light-red" }
# "hint" = { fg = "black", bg = "light-blue" }

"diagnostic.warning" = { fg = "black", bg = "light-yellow" }
"diagnostic.error" = { fg = "black", bg = "light-red" }
"diagnostic.hint" = { fg = "black", bg = "light-blue" }
"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


# "function" = {fg = "black", bg = "black"}

# "variable.other.member" = { fg = "yellow1" }

"function" = { bg = "#3D3DB8" }
"keyword.control" = { fg = "black", bg = "#FA7970" }

# "function.builtin" = { bg = "yellow1" }
# "function.macro" = { bg = "blue1" }

# "keyword" = { bg = "red1" }
# "keyword.control.import" = { bg = "aqua1" }
